name: Draw Keymap

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - config/keymap.keymap
      - boards/shields/torabo_tsuki_lp/torabo_tsuki_lp_layouts.dtsi
      - .github/workflows/draw.yml

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@3a4ca7e060a54ba700d3e7b6a43cb0b9cec347d2
    permissions:
      contents: write
    with:
      commit_message: "📝 docs: update keymap diagram"
      amend_commit: false
      keymap_patterns: config/keymap.keymap
      draw_args: "keymap:'-d boards/shields/torabo_tsuki_lp/torabo_tsuki_lp_layouts.dtsi -l physical_layout_s'"
      output_folder: keymap-drawer
      destination: both
      fail_on_error: true
